
[functions.verify-korapay-payment]
enabled = true
verify_jwt = true
import_map = "./functions/verify-korapay-payment/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/verify-korapay-payment/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/verify-korapay-payment/*.html" ]

[functions.initialize-korapay-charge]
enabled = true
verify_jwt = true
import_map = "./functions/initialize-korapay-charge/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/initialize-korapay-charge/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/initialize-korapay-charge/*.html" ]
